# install_apache2.yml
- name: Installer Apache2 sur Debian, Ubuntu ou CentOS
  hosts: all
  become: true
  tasks:

    - name: Installer apache2 sur Debian/Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer httpd (Apache) sur CentOS/RHEL
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Activer et démarrer apache2 sur Debian/Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Activer et démarrer httpd sur CentOS/RHEL
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ouvrir le port 80 dans firewalld (HTTP) sur CentOS/RHEL
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: Vérifier que httpd écoute sur le port 80 (CentOS/RHEL)
      shell: ss -tuln | grep :80
      register: apache_port_check
      failed_when: apache_port_check.rc != 0
      when: ansible_facts['os_family'] == "RedHat"
